import React, { useState } from 'react'
import { useHistory } from 'react-router-dom'
import { Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Paper, Grid, Typography, TablePagination, TableFooter } from '@material-ui/core';
import { makeStyles } from '@material-ui/core/styles';
import ViewEditDialog from './../../Dialog/ViewEditDialog';
import Axios from 'axios'
import ConfirmDialog from './../../Dialog/ConfirmDialog';
import SuccessDialog from './../../Dialog/SuccessDialog';
import Notification from './../../Dialog/Notification';
import LoginAuthPop from './../../Dialog/LoginAuthPop';
import PopUp from './../../Dialog/PopUp';
import { FaEdit } from 'react-icons/fa';
import Moment from 'react-moment'
const useStyles = makeStyles((theme) => ({ table: { minWidth: 200, }, tableContainer: { maxWidth: 1175, borderRadius: 0, border: "0.5px solid #d5dbd9" }, tableHeaderCell: { fontWeight: 'bold', backgroundColor: '#0061a8', color: theme.palette.getContrastText(theme.palette.primary.dark), fontFamily: "Montserrat, sans-serif", cursor: "pointer", lineHeight: "1.43", paddingTop: "15px", paddingBottom: "15px" }, tableCell: { fontFamily: "Montserrat, sans-serif", cursor: "pointer", }, avatar: { backgroundColor: theme.palette.primary.light, color: theme.palette.getContrastText(theme.palette.primary.light) }, name: { cursor: "pointer", fontWeight: 'bold', color: "#2e4a56", fontFamily: "Montserrat, sans-serif" }, residentIdTitle: { fontSize: "15px" }, status: { fontWeight: 'bold', fontSize: '0.75rem', color: 'white', backgroundColor: 'grey', borderRadius: 5, padding: '3px 10px', display: 'inline-block', fontFamily: "Montserrat, sans-serif", } }))
export default function EmergencyTable({ data }) {
    Axios.defaults.withCredentials = true;
    const classes = useStyles(), history = useHistory(), [page, setPage] = useState(0), [rowsPerPage, setRowsPerPage] = useState(5), [viewEditDialog, setViewEditDialog] = useState({ isOpen: !1, title: "", subtitle: "", yesButton: "", noButton: "" }), [confirmDialog, setConfirmDialog] = useState({ isOpen: !1, title: "", subtitle: "", yesButton: "", noButton: "" }), [successDialog, setSuccessDialog] = useState({ isOpen: !1, title: "", subtitle: "", yesButton: "", noButton: "" }), [errorDialog, setErrorDialog] = useState({ isOpen: !1, title: "", subtitle: "", yesButton: "", noButton: "" }), [notify, setNotify] = useState({ isOpen: !1, message: "", type: "" }), handleChangePage = (e, t) => { setPage(t) }, handleChangeRowsPerPage = e => { setRowsPerPage(+e.target.value); setPage(0) }, refresh = () => { setSuccessDialog({ ...successDialog, isOpen: !1 }); history.push("/resident-reports") }, [incident_location, setIncidentLocation] = useState(""), [incident_description, setIncidentDescription] = useState(""), [date_submitted, setDateSubmitted] = useState(""), [first_name, setFirstName] = useState(""), [middle_name, setMiddleName] = useState(""), [last_name, setLastName] = useState(""), [suffix, setSuffix] = useState(""), [openPopup, setOpenPopup] = useState(!1), [report_id, setReportId] = useState("");
    const openInPopup = (resident_report_id, date_submitted, last_name, first_name, middle_name, suffix, incident_location, incident_description) => { setOpenPopup(true); setIncidentLocation(incident_location); setIncidentDescription(incident_description); setFirstName(first_name); setMiddleName(middle_name); setLastName(last_name); setSuffix(suffix); setDateSubmitted(date_submitted); setReportId(resident_report_id); }
    const delete_report_confirm = () => { setConfirmDialog({ ...confirmDialog, isOpen: false }); Axios.delete(`http://localhost:3001/deleteEmergency/${report_id}`).then((response) => { if (response.data.err || response.data.err2) { setErrorDialog({ isOpen: true, title: response.data.err, subtitle: "Please check your connection and try again.", noButton: <button onClick={() => setErrorDialog({ ...errorDialog, isOpen: false })} className="alert_backBtn">Back</button> }) } else if (response.data.success) { setSuccessDialog({ isOpen: true, title: "Delete Report", subtitle: response.data.success, noButton: <button onClick={() => refresh()} className="alert_backBtn">Back</button> }) } else { setErrorDialog({ isOpen: true, title: "Connection Error", subtitle: "Please check your connection and try again.", noButton: <button onClick={() => setErrorDialog({ ...errorDialog, isOpen: false })} className="alert_backBtn">Back</button> }) } }) }
    const delete_report = () => { setConfirmDialog({ isOpen: true, title: 'Are you sure you want to delete this Report?', subtitle: 'Deleting report cannot be undone.', noButton: <button onClick={() => setConfirmDialog({ ...confirmDialog, isOpen: false })} className="alert_noBtn"> No </button>, yesButton: <button onClick={delete_report_confirm} className="alert_yesBtn"> Yes </button>, }) }
    return (
        <div>
            <ViewEditDialog viewEditDialog={viewEditDialog} setViewEditDialog={setViewEditDialog} />
            <ConfirmDialog confirmDialog={confirmDialog} setConfirmDialog={setConfirmDialog} />
            <SuccessDialog successDialog={successDialog} setSuccessDialog={setSuccessDialog} />
            <LoginAuthPop errorDialog={errorDialog} setErrorDialog={setErrorDialog} />
            <Notification notify={notify} setNotify={setNotify} />
            <PopUp title="Emergency Reports" openPopup={openPopup} setOpenPopup={setOpenPopup}> <div className="wrapper" id="wrapper_profile"> <div className="forms" id="inputfields_profile"> <div className="input_fields"> <label>Reported By</label> <textarea type="text" className="textarea" required autoComplete="off" disabled value={last_name + ", " + first_name + " " + middle_name + " " + suffix} /> </div><div className="input_fields"> <label>Location Of Emergency</label> <textarea type="text" className="textarea" required autoComplete="off" disabled value={incident_location} /> </div><div className="input_fields"> <label>Emergency Description</label> <textarea type="text" className="textarea" required autoComplete="off" disabled value={incident_description} /> </div><div className="input_fields"> <label>Date Submitted: </label> <p className="inputs"><Moment format={"MMMM DD, YYYY"} date={date_submitted} /></p></div></div></div><div className="add_resident_container_footer" id="mobile_hidden"> <div className="wrapper" id="wrapper_profile"> <div className="forms" id="inputfields_profile"> <div className="input_fields" > <input type="submit" value="Delete Report" className="editProfile_btn" onClick={delete_report} /> </div></div></div></div></PopUp>
            <TableContainer component={Paper} className={classes.tableContainer}> <Table className={classes.table} aria-label="simple table"> <TableHead> <TableRow> <TableCell className={classes.tableHeaderCell}>Reported By</TableCell> <TableCell className={classes.tableHeaderCell}>Incident Date</TableCell> <TableCell className={classes.tableHeaderCell}>Incident Time</TableCell> <TableCell className={classes.tableHeaderCell} id="mobile_hidden">Action</TableCell> </TableRow> </TableHead> <TableBody>{data.slice(page * rowsPerPage, page * rowsPerPage + rowsPerPage).map((row) => { return (<TableRow > <TableCell style={{ cursor: 'pointer' }} onClick={() => openInPopup(row.resident_report_id, row.date_submitted, row.last_name, row.first_name, row.middle_name, row.suffix, row.incident_location, row.incident_description)}> <Grid container> <Grid item lg={10}> <Typography className={classes.name} style={{ cursor: 'pointer' }}>{row.last_name + ", " + row.first_name + " " + row.middle_name + " " + row.suffix}</Typography> </Grid> </Grid> </TableCell> <TableCell className={classes.tableCell}> <p className="inputs"><Moment format={"MMMM DD, YYYY"} date={row.incident_date} /></p></TableCell> <TableCell className={classes.tableCell}>{row.incident_time}</TableCell> <TableCell id="mobile_hidden"> <button className="view_edit" onClick={() => openInPopup(row.resident_report_id, row.date_submitted, row.last_name, row.first_name, row.middle_name, row.suffix, row.incident_location, row.incident_description)}><FaEdit /></button> </TableCell> </TableRow>) })}</TableBody> <TableFooter> <TablePagination rowsPerPageOptions={[5, 10, 15]} component="div" count={data.length} rowsPerPage={rowsPerPage} page={page} onPageChange={handleChangePage} onRowsPerPageChange={handleChangeRowsPerPage} /> </TableFooter> </Table> </TableContainer>
        </div>
    )
}